version: '3.8'
services:
  backend:
    build: ./Backend
    ports:
      - "5000:5000"
    volumes:
      - ./Backend:/app
    environment:
      - FLASK_ENV=development
  frontend:
    build: ./frontend
    ports:
      - "80:80"
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ai_job_platform
    ports:
      - "5432:5432"
    volumes:
      - ./database/schema.sql:/docker-entrypoint-initdb.d/schema.sql
      - ./database/migrations:/migrations

